
name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

env:
  DOCKER_BUILDKIT: 1
  AUTHENTICATION: "${{ secrets.PROD_AUTHENTICATION }}"
  TOKEN: "${{ secrets.PROD_TOKEN }}"
  PACKAGE: ${{ secrets.PROD_PACKAGE }}

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-24.04
    #runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          set -x
          #https://github.com/orgs/community/discussions/116610
          docker compose -f docker-compose.yaml build --no-cache --progress=plain
          docker compose -f docker-compose.yaml run appimage make all

      - name: Get appimagetool
        run: |
          set -x
          version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
          echo "version_go_appimage: $version_go_appimage"
          wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Extract AppImage and rebuilt to remove need of libfuse.so.2
        run: |
          set -x
          cd app/
          pwd; ls -lah

          fileName=$(ls MasterPDFEditor*.AppImage)
          #chmod +x "$fileName"
          ./"$fileName" --appimage-extract
          rm MasterPDFEditor*.AppImage MasterPDFEditor*.AppImage.md5
          pwd; ls -lah

          #cat squashfs-root/MasterPDFEditor.desktop
          #sed -i 's/=Master PDF Editor 5/=MasterPDFEditor/g' squashfs-root/MasterPDFEditor.desktop
          #cat squashfs-root/MasterPDFEditor.desktop

          mv ../appimagetool-x86_64.AppImage .
          version=$(echo "$fileName" | cut -d '-' -f2) # Cut version
          tag=1 #1

          ARCH=x86_64 VERSION="${version}-${tag}_JB" ./appimagetool-x86_64.AppImage squashfs-root/
          pwd; ls -lah

          fileName=$(ls MasterPDFEditor*.AppImage)
          echo "fileName: $fileName"
          md5sum "$fileName" > "${fileName}.md5"

          # Fedora Gnome version - withou /lib64/
          rm -r squashfs-root/lib64/
          ARCH=x86_64 VERSION="${version}-Fedora-${tag}_JB" ./appimagetool-x86_64.AppImage squashfs-root/
          pwd; ls -lah

          PDF_Name=$(ls MasterPDFEditor-*.pdf | cut -d '.' -f1)
          mv MasterPDFEditor-*.pdf $PDF_Name-${version}.pdf

          fileName=$(ls MasterPDFEditor*-Fedora-*.AppImage)
          echo "fileName: $fileName"
          md5sum "$fileName" > "${fileName}.md5"
          pwd; ls -lah

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./app/MasterPDFEditor-*.AppImage; ./app/MasterPDFEditor-*.md5; ./app/MasterPDFEditor-*.zsync; ./app/MasterPDFEditor-*.pdf"
          #overwrite: true
          verbose: true
          draft: false
          default_release_name: "MasterPDFEditor V in AppImage"
